services:
  client-db:
    image: postgres:16
    container_name: client-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: clients
      POSTGRES_USER: client_user
      POSTGRES_PASSWORD: client_pass
    volumes:
      - client-db-data:/var/lib/postgresql/data

  employee-db:
    image: postgres:16
    container_name: employee-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: employee_pass
    volumes:
      - employee-db-data:/var/lib/postgresql/data

  request-db:
    image: postgres:16
    container_name: request-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: requests
      POSTGRES_USER: request_user
      POSTGRES_PASSWORD: request_pass
    volumes:
      - request-db-data:/var/lib/postgresql/data

volumes:
  client-db-data:
  employee-db-data:
  request-db-data: