server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: client-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/clients/**
            - id: employee-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/employees/**
            - id: request-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/products/**,/api/requests/**

management:
  endpoints:
    web:
      exposure:
        include: health, info
